<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseManager.Contracts\WarehouseManager.Contracts.csproj" />
    <ProjectReference Include="..\WarehouseManager.Domain\WarehouseManager.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mappings\" />
    <Folder Include="Validators\" />
    <Folder Include="Features\" />
    <Folder Include="DTO\" />
    <Folder Include="Common\" />
  </ItemGroup>

</Project>
