<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="Endpoints\" />
    <Folder Include="Extensions\" />
    <Folder Include="Controllers\" />
    <Folder Include="Configuration\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseManager.Application\WarehouseManager.Application.csproj" />
    <ProjectReference Include="..\WarehouseManager.Contracts\WarehouseManager.Contracts.csproj" />
    <ProjectReference Include="..\WarehouseManager.Infrastructure\WarehouseManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
