// <auto-generated />
using System;
using AlmazManager.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlmazManager.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlmazManager.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CanArchiveMaterials")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCancelDocuments")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageMaterials")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageSupplies")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanPermanentlyDeleteMaterials")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRestoreMaterials")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.InventoryDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("InventoryDocuments", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.InventoryDocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("InventoryDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("InventoryDocumentId", "MaterialId")
                        .IsUnique();

                    b.ToTable("InventoryDocumentItems", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ColorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("MachineName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("MinimumQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal?>("PackageLiters")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WidthMeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("Article")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("Kind");

                    b.HasIndex("Kind", "MachineName", "ColorName", "PackageLiters");

                    b.HasIndex("Name");

                    b.HasIndex("Kind", "ColorCode", "WidthMeters");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.SupplyInvoiceItem", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlmazManager.Domain.Entities.SupplyInvoice", null)
                        .WithMany("Items")
                        .HasForeignKey("SupplyInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.AppUser", null)
                        .WithOne()
                        .HasForeignKey("AlmazManager.Domain.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("QuantityAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("QuantityBefore")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid?>("ReversedOperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.UserCategoryAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanInventoryOracal")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanInventoryStandard")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanIssue")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanReceive")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId")
                        .IsUnique();

                    b.ToTable("UserCategoryAccesses", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<Guid?>("DocumentId").HasColumnType("uuid");
                    b.Property<Guid>("EntityId").HasColumnType("uuid");
                    b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<Guid?>("MaterialId").HasColumnType("uuid");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAtUtc");
                    b.HasIndex("DocumentId");
                    b.HasIndex("MaterialId");
                    b.HasIndex("UserId");
                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("DeduplicationKey").HasMaxLength(250).HasColumnType("character varying(250)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<Guid?>("MaterialId").HasColumnType("uuid");
                    b.Property<string>("Message").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<DateTime?>("ReadAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("ResolvedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("SupplyInvoiceId").HasColumnType("uuid");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<int>("Type").HasColumnType("integer");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "DeduplicationKey", "ResolvedAtUtc");
                    b.HasIndex("UserId", "ReadAtUtc");
                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.SupplyInvoice", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<string>("AttachmentPath").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("Comment").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("CreatedByUserId").HasColumnType("uuid");
                    b.Property<DateOnly?>("ExpectedDeliveryDate").HasColumnType("date");
                    b.Property<DateOnly>("InvoiceDate").HasColumnType("date");
                    b.Property<string>("InvoiceNumber").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<DateOnly?>("PaymentDueDate").HasColumnType("date");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<string>("Supplier").IsRequired().HasMaxLength(250).HasColumnType("character varying(250)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ExpectedDeliveryDate");
                    b.HasIndex("PaymentDueDate");
                    b.HasIndex("Status");
                    b.HasIndex("Supplier", "InvoiceNumber", "InvoiceDate").IsUnique();
                    b.ToTable("SupplyInvoices", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.SupplyInvoiceItem", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<decimal>("ExpectedQuantity").HasPrecision(18, 3).HasColumnType("numeric(18,3)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<Guid>("MaterialId").HasColumnType("uuid");
                    b.Property<decimal>("ReceivedQuantity").HasPrecision(18, 3).HasColumnType("numeric(18,3)");
                    b.Property<Guid>("SupplyInvoiceId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("MaterialId");
                    b.HasIndex("SupplyInvoiceId", "MaterialId").IsUnique();
                    b.ToTable("SupplyInvoiceItems", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("CategoryOrderJson").IsRequired().HasColumnType("jsonb");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("MaterialOrderJson").IsRequired().HasColumnType("jsonb");
                    b.Property<int>("Theme").HasColumnType("integer");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.WarehouseDocumentSequence", b =>
                {
                    b.Property<int>("Type")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");
                    b.Property<int>("LastNumber").HasColumnType("integer");
                    b.HasKey("Type");
                    b.ToTable("WarehouseDocumentSequences", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.WarehouseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Supplier")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("SupplyInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SupplyInvoiceId");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("\"SequenceNumber\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("WarehouseDocuments", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.WarehouseDocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("DocumentId", "MaterialId")
                        .IsUnique();

                    b.ToTable("WarehouseDocumentItems", (string)null);
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.InventoryDocumentItem", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.InventoryDocument", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmazManager.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.Material", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.UserCategoryAccess", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmazManager.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.WarehouseDocument", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.WarehouseDocumentItem", b =>
                {
                    b.HasOne("AlmazManager.Domain.Entities.WarehouseDocument", null)
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmazManager.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.InventoryDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.SupplyInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlmazManager.Domain.Entities.WarehouseDocument", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
